name: Deploy Frontend to cPanel

on:
  push:
    branches:
      - main
    paths:
      - "frontend/react-frontend/**" # Updated path
  workflow_dispatch: # Allows manual triggering of this workflow

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      # Step 3: Install dependencies
      - name: Install Dependencies
        working-directory: ./frontend/react-frontend # Updated path
        run: |
          npm install
          npm ci

      # Step 4: Build React app
      - name: Build React App
        working-directory: ./frontend/react-frontend # Updated path
        run: |
          CI=false npm run build # Prevent ESLint warnings from failing the build

      # Step 5: Create .htaccess for React routing
      - name: Create .htaccess
        working-directory: ./frontend/react-frontend/build # Updated path
        run: |
          echo "Options -MultiViews" > .htaccess
          echo "RewriteEngine On" >> .htaccess
          echo "RewriteCond %{REQUEST_FILENAME} !-f" >> .htaccess
          echo "RewriteRule ^ index.html [QSA,L]" >> .htaccess

      # Step 6: Deploy to cPanel via FTP
      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.CPANEL_SERVER }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          local-dir: ./frontend/react-frontend/build/ # Updated path
          server-dir: /public_html/
          dangerous-clean-slate: true
